apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: database
spec:
  serviceName: "postgres"  # Required for StatefulSet service discovery
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres  # Ensure the label matches the selector
      annotations:
        force-restart: "{{randAlphaNum 5}}"  # ✅ Triggers restart on every sync
