apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: api
  annotations:
    rollout/restart: "{{now | unixEpoch}}"  # ✅ This changes on every update, forcing a restart
data:
  config.yaml: |
    mappings:
      - api_endpoint: /myapi
        query: "SELECT * FROM mytable;"
        columns:
          id: myapi_id
          name: myapi_name
          created_at: myapi_created_at
      - api_endpoint: /myapi6
        query: "SELECT id, name, created_at FROM othertable;"
        columns:
          id: myapi2_id
          name: myapi2_name
          created_at: myapi2_created_at
