mappings:
  - api_endpoint: /myapi
    query: "SELECT * FROM mytable;"
    columns:
      id: myapi_id
      name: myapi_name
      created_at: myapi_created_at

  - api_endpoint: /myapi2
    query: "SELECT id, name, created_at FROM othertable;"
    columns:
      id: myapi2_id
      name: myapi2_name
      created_at: myapi2_created_at