apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - api-config.yaml
  - deployment.yaml
  - service.yaml

patches:
  - target:
      kind: Deployment
      name: anti-corruption-layer
      namespace: api
    path: rollout-patch.yaml
