apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: api-config
    namespace: api
    files:
      - config.yaml  # ✅ Generate ConfigMap dynamically instead of a static YAML file
    options:
      annotations:
        config-hash: "{{`{{ .Files.Get \"config.yaml\" | sha256sum }}`}}"  # ✅ Forces pod restart when ConfigMap changes

patches:
  - target:
      kind: Deployment
      name: anti-corruption-layer
      namespace: api
    path: rollout-patch.yaml

